import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { useState } from "react"
// import { useRouter } from "next/router"
import AddNewCat from "./components/AddNewCat"
import AddResources from "./components/AddResources"
import Table from "./components/Table"
import styles from "../styles/Home.module.css"

export default function Dashboard(props) {
  const [showTable, setShowTable] = useState(false)
  const [viewCatForm, setViewCatForm] = useState(false)
  const [addResources, setAddResources] = useState(false)
  const [gatos, setGatos] = useState([])

  /* 
  gatos há de ser um array de 
  {
      name: "string",
  }
  */

  return (
    <div >
      <Head>
        <title>CATSTOCK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Flatcat.ico" />
      </Head>

      <div>
        <div>.</div>
        <div>.</div>
        <div>.</div>
        <div>
          <div className={styles.resourceContainer}>
            <div className={styles.foodContainer}>
              <div className={styles.resourceFont}>1000kg</div>
              <div className={styles.resourceTitle}>Food</div>
              <div className={styles.resourceInfo}>Comsumption expectance</div>
              <div className={styles.resourceDate}>2 Weeks</div>
            </div>
            <div className={styles.sandContainer}>
            <div className={styles.resourceFont}>1000kg</div>
              <div className={styles.resourceTitle}>Food</div>
              <div className={styles.resourceInfo}>Comsumption expectance</div>
              <div className={styles.resourceDate}>2 Weeks</div>
            </div>
            <div className={styles.cleanContainer}>
            <div className={styles.resourceFont}>1000kg</div>
              <div className={styles.resourceTitle}>Food</div>
              <div className={styles.resourceInfo}>Comsumption expectance</div>
              <div className={styles.resourceDate}>2 Weeks</div>
            </div>
            <div className={styles.capitalContainer}>
            <div className={styles.resourceFont}>1000kg</div>
              <div className={styles.resourceTitle}>Food</div>
              <div className={styles.resourceInfo}>Comsumption expectance</div>
              <div className={styles.resourceDate}>2 Weeks</div>
            </div>
          </div>

          <div>.</div>
          <div>.</div>
          <div>.</div>
          <div className={styles.divButton}>
            <button className={styles.button}
              onClick={() => setShowTable(!showTable)}>{showTable ? "Show Table" : "Hide Table"}
            </button>
            {showTable && <div>
              <Table
                gatos
                setShowTable
                showTable
              />
            </div>}

            <button className={styles.button}
              onClick={() => setViewCatForm(!viewCatForm)}>add new cat</button>{viewCatForm && <div>
                <AddNewCat setGatos viewCatForm setViewCatForm />
              </div>}

            <button className={styles.button}
              onClick={() => setAddResources(!addResources)}>Add resources</button>{addResources && <AddResources addResources setAddResources />}

          </div>
          <div className={styles.bottomDiv}>

          </div>
        </div>


      </div>



    </div>)
}


// Aqui vai ser o cabeçalho, meter os botoes add gato, add recursos, podes delete gatos e recursos? 