import Head from 'next/head'
import Dashboard from './Dashboard'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head >
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Flatcat.ico" />
      </Head>

      <main >
        <header className={styles.header}>
          <img src='/CatStock.svg' />
        </header>

        <aside className='menuBar'>

          {/* <Menu />
    */}

        </aside>
        <content className='mainPage'>
          <Dashboard
          />
        </content>
      </main>

    </>


  )
}