import Head from 'next/head'
import Dashboard from './Dashboard'



export default function Home() {
  return (
    <>

    <Head>
    <title>OPPLOG</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/logo.ico" />
  </Head>

  <main >

  <header >
    
    CATSTOCK
      
    

     </header>

    <aside className='menuBar'>

    {/* <Menu />
    */}

    </aside>

    <content className='mainPage'>
    <Dashboard
   
     />

    </content>

    </main>

    </>
    

  )
}