// import Head from 'next/head'
// // import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import {useState} from "react"

// export default function Dashboard() {
//     const [gatos, setGatos] = useState({
//         Nome: "string",
//         Idade: "number",
//         Raça: "string",
//         desparazitante: "data",
//         gastos : {
//             comida: "",
//             agua: "",
//             areia: "",
//             desparazitante: ""
//         }
//     })
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>CatStash</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//     <div>Aqui vai ser o cabeçalho, meter os botoes add gato, add recursos, podes delete gatos e recursos?</div>
//     <div>aqui vao estar as bolas:
//     <div>Comida</div>
//     <div>Areia</div>
//     <div>Agua</div>
//     <div>Capital</div>

//     </div>
//     <button onClick={() => setShowTable(true)}>mostrar gatos</button>
//     <div>Aqui vai a tabela com os gatos, fazer com componentes</div>

// </div>)}